# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.1.$(Rev:r)

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: Signereno/devops_templates
      endpoint: Idfy

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: Release

steps:
- template: dotnet/build_individual_projects.yml@templates
  parameters:
    projects:
      - 'src/Idfy.QuartzExtensions/Idfy.QuartzExtensions.Core/Idfy.QuartzExtensions.Core.csproj'
      - 'src/Idfy.QuartzExtensions/Idfy.QuartzExtensions.PostgreSql/Idfy.QuartzExtensions.PostgreSql.csproj'
      - 'src/Idfy.QuartzExtensions/Idfy.QuartzExtensions.SqlServer/Idfy.QuartzExtensions.SqlServer.csproj'
- task: PublishSymbols@2
  inputs:
    SearchPattern: '**/bin/**/*.pdb'
    SymbolServerType: 'TeamServices'
